# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddCamera.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddCamera(object):
    def setupUi(self, AddCamera):
        AddCamera.setObjectName("AddCamera")
       # AddCamera.resize(354, 406)
        self.setFixedSize(354, 406)
        self.layoutWidget = QtWidgets.QWidget(AddCamera)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 5, 336, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.list = QtWidgets.QListView(self.layoutWidget)
        self.list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.list.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.list.setObjectName("list")

        self.verticalLayout.addWidget(self.list)
        self.groupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox.setObjectName("groupBox")

        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(50, 20, 241, 31))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_3.setSpacing(10)
        self.bt1 = QtWidgets.QPushButton(self.widget)
        #self.bt1.setGeometry(QtCore.QRect(10, 20, 60, 30))
        #self.bt1.setMinimumSize(QtCore.QSize(50, 30))
        self.bt1.setMaximumSize(QtCore.QSize(60, 30))
        self.bt1.setObjectName("bt1")
        self.horizontalLayout_3.addWidget(self.bt1)

        self.bt_Add = QtWidgets.QPushButton(self.widget)
        self.bt_Add.setMaximumSize(QtCore.QSize(60, 30))
        self.bt_Add.setObjectName("bt_Add")
        self.horizontalLayout_3.addWidget(self.bt_Add)

        self.bt_Edit = QtWidgets.QPushButton(self.widget)
        self.bt_Edit.setMaximumSize(QtCore.QSize(60, 30))
        self.bt_Edit.setObjectName("bt_Edit")
        self.horizontalLayout_3.addWidget(self.bt_Edit)

        self.bt_delete = QtWidgets.QPushButton(self.widget)
        self.bt_delete.setMaximumSize(QtCore.QSize(60, 30))
        self.bt_delete.setObjectName("bt_delete")
        self.horizontalLayout_3.addWidget(self.bt_delete)
        self.bt_close = QtWidgets.QPushButton(self.widget)
        self.bt_close.setMaximumSize(QtCore.QSize(60, 30))
        self.bt_close.setObjectName("bt_close")
        self.horizontalLayout_3.addWidget(self.bt_close)
        self.verticalLayout.addWidget(self.groupBox)
        self.retranslateUi(AddCamera)
        QtCore.QMetaObject.connectSlotsByName(AddCamera)

    def retranslateUi(self, AddCamera):
        _translate = QtCore.QCoreApplication.translate
        AddCamera.setWindowTitle(_translate("AddCamera", "Form"))
        self.groupBox.setTitle(_translate("AddCamera", "Camera Operations"))
        self.bt1.setText(_translate("AddCamera", "Start"))
        self.bt_Add.setText(_translate("AddCamera", "Add"))
        self.bt_Edit.setText(_translate("AddCamera", "Edit"))
        self.bt_delete.setText(_translate("AddCamera", "Delete"))
        self.bt_close.setText(_translate("AddCamera", "Close"))
