# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'NewCameraDlg.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_NewCameraDlg(object):
    def setupUi(self, NewCameraDlg):
        NewCameraDlg.setObjectName("NewCameraDlg")
        NewCameraDlg.resize(463, 252)
        self.label = QtWidgets.QLabel(NewCameraDlg)
        self.label.setGeometry(QtCore.QRect(30, 20, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(NewCameraDlg)
        self.label_2.setGeometry(QtCore.QRect(30, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.txtName = QtWidgets.QLineEdit(NewCameraDlg)
        self.txtName.setGeometry(QtCore.QRect(140, 10, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtName.setFont(font)
        self.txtName.setObjectName("txtName")
        self.txtPlatUrl = QtWidgets.QLineEdit(NewCameraDlg)
        self.txtPlatUrl.setGeometry(QtCore.QRect(140, 60, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.txtPlatUrl.setFont(font)
        self.txtPlatUrl.setObjectName("txtPlatUrl")
        self.btnReset = QtWidgets.QPushButton(NewCameraDlg)
        self.btnReset.setGeometry(QtCore.QRect(120, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnReset.setFont(font)
        self.btnReset.setObjectName("btnReset")
        self.btnAdd = QtWidgets.QPushButton(NewCameraDlg)
        self.btnAdd.setGeometry(QtCore.QRect(220, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnAdd.setFont(font)
        self.btnAdd.setObjectName("btnAdd")
        self.btnCancel = QtWidgets.QPushButton(NewCameraDlg)
        self.btnCancel.setGeometry(QtCore.QRect(320, 190, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.btnCancel.setFont(font)
        self.btnCancel.setObjectName("btnCancel")
        self.camloc = QtWidgets.QComboBox(NewCameraDlg)
        self.camloc.setGeometry(QtCore.QRect(140, 110, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.camloc.setFont(font)
        self.camloc.setEditable(True)
        self.camloc.setCurrentText("")
        self.camloc.setObjectName("camloc")

        self.retranslateUi(NewCameraDlg)
        QtCore.QMetaObject.connectSlotsByName(NewCameraDlg)

    def retranslateUi(self, NewCameraDlg):
        _translate = QtCore.QCoreApplication.translate
        NewCameraDlg.setWindowTitle(_translate("NewCameraDlg", "Add Camera"))
        self.label.setText(_translate("NewCameraDlg", "Camera Name:"))
        self.label_2.setText(_translate("NewCameraDlg", "Camera URL:"))
        self.btnReset.setText(_translate("NewCameraDlg", "&Reset"))
        self.btnAdd.setText(_translate("NewCameraDlg", "&Ok"))
        self.btnCancel.setText(_translate("NewCameraDlg", "&Cancel"))
        