[TELEGRAM]
APITOKEN = 8086468462:AAG_ZOxPJ3Qgfd-ac1cVLK7sfsgROhVquYQ
CHAT_ID = -4859906853
; APITOKEN = 5789741206:AAF9pFjvgZcftdQOnlhysC2oOcd9clkHSds
; CHAT_ID = -4268254544

[MYSQL_DB_NAME]
DB_NAME = bothra_ppe_detection

[MODEL]
PERSON_MODEL = .\Detection\model\person_detection.pt
PPE_MODEL = .\Detection\model\ppe_detection.pt

[THRESHOLD]
MIN_THRESHOLD = 0.20
PPE_THRESHOLD = 0.20

[COCO_PATH]
CLASS_FILE = .\Detection\data\coco.yaml

[OBJECTS]
TARGET_OBJECTS = person
IMP_PPE = no_helmet,no_vest

[LIVE_FRAME_RESOLUTION]
WIDTH_AND_HEIGHT = [1300,740]

[DEFAULT_POPUP_GIF]
DEFAULT_GIF = ppe

[DETECTED_DATA]
DETECTED_DATA_PATH = .\DetectedData

[TIME_CHUNKS]
TIME_LIMIT = 10

[HANDLE FRAME]
FRAME_SKIP = 0

[PREVIOUS_FRAME_STORAGE]
MAX_LEN = 100

[TIME_DURATION_VIDEO_RECORD]
TIME = 10

[RECORD_VIDEO_RESOLUTION]
SCALE = 0.25

